# Generated by Django 4.1 on 2024-06-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_address", models.CharField(max_length=50)),
                ("user_phoneNumber", models.CharField(max_length=50)),
                ("user_email", models.EmailField(max_length=50)),
                ("user_password", models.CharField(max_length=50)),
                ("user_name", models.CharField(max_length=50)),
                ("user_role", models.CharField(max_length=50)),
                ("user_enterYear", models.DateTimeField()),
            ],
        ),
    ]
