# Generated by Django 4.1 on 2024-06-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="user_password",
        ),
        migrations.AddField(
            model_name="users",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="password",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="user_email",
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="user_enterYear",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="users",
            name="user_name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
