# Generated by Django 4.1 on 2024-06-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0002_remove_users_user_password_users_last_login_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="user_enterYear",
            field=models.DateField(blank=True, null=True),
        ),
    ]
