# Generated by Django 4.1 on 2024-06-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("supplier_id", models.AutoField(primary_key=True, serialize=False)),
                ("supplier_name", models.CharField(max_length=50)),
                ("supplier_address", models.CharField(max_length=50)),
                ("supplier_phoneNumber", models.CharField(max_length=50)),
            ],
        ),
    ]
