# Generated by Django 4.1 on 2024-06-02 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                ("shipment_id", models.AutoField(primary_key=True, serialize=False)),
                ("shipment_date", models.DateTimeField()),
                ("order_status", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ShipmentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_date", models.DateTimeField()),
                ("detail_qty", models.IntegerField()),
                ("product_name", models.CharField(max_length=50)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shipment.shipment",
                    ),
                ),
            ],
            options={
                "unique_together": {("shipment", "product")},
            },
        ),
    ]
