# Generated by Django 4.1 on 2024-06-03 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="order_totalCost",
            new_name="order_totalcost",
        ),
        migrations.RemoveField(
            model_name="order",
            name="expected_arrivalDate",
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="supplier_sellingprice",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="description",
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="expected_arrivaldate",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
