# Generated by Django 4.1 on 2024-06-04 06:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_rename_product_selling_price_product_product_sellingprice"),
        ("suppliers", "0001_initial"),
        ("orders", "0002_rename_order_totalcost_order_order_totalcost_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="orderdetail",
            unique_together={("order", "product", "supplier")},
        ),
    ]
