# Generated by Django 4.1 on 2024-06-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deliveries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="delivery_date",
            field=models.DateField(),
        ),
    ]
