# Generated by Django 4.1 on 2024-06-04 06:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0002_rename_order_totalcost_order_order_totalcost_and_more"),
        ("products", "0002_rename_product_selling_price_product_product_sellingprice"),
        ("deliveries", "0002_alter_delivery_delivery_date"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="deliverydetail",
            unique_together={("delivery", "product", "order", "user")},
        ),
    ]
