# Generated by Django 4.1 on 2024-06-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=50)),
                (
                    "product_selling_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("product_volume", models.CharField(max_length=50)),
                ("product_qty", models.IntegerField()),
                (
                    "product_weight",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("product_minQty", models.IntegerField()),
                ("product_location", models.CharField(max_length=50)),
                ("product_category", models.CharField(max_length=50)),
                (
                    "maintenance_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
    ]
