# Generated by Django 4.1 on 2024-06-03 19:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="product_selling_price",
            new_name="product_sellingprice",
        ),
    ]
